name: Level 1 - Yoshi's Island

on:
  workflow_dispatch: {} # TODO: Bonus opdracht, vervang door een echte trigger.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5.3.0
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        run: gradle wrapper

      - name: Build with Gradle
        run: ./gradlew build