name: Level 3a - Boo's Haunted Mansion

on:
  workflow_dispatch: {}

jobs:
  quality-gate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Rune Gradle tests
        env:
          JACOCO_MINIMUM_COVERAGE: 0.6
        run: gradle test jacocoTestReport jacocoTestCoverageVerification

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            build/test-results/test
            build/reports/tests/test
        

        # TODO - Run de testen

        # TODO - Hanteer een minimale code coverage

        # TODO - Genereer een JaCoCo rapport

        # TODO - Upload het rapport voor analyse